# Generated by Django 5.0.3 on 2024-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blogId', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('ipAddress', models.CharField(max_length=255)),
                ('userAgent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'BlogViews',
            },
        ),
    ]
