# Generated by Django 5.0.3 on 2024-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gameName', models.CharField(max_length=255)),
                ('yearPublished', models.IntegerField()),
                ('gameplay', models.IntegerField()),
                ('storytelling', models.IntegerField()),
                ('characterDesign', models.IntegerField()),
                ('graphics', models.IntegerField()),
                ('soundDesign', models.IntegerField()),
                ('suspense', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('replayability', models.IntegerField()),
                ('emotionalImpact', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('overallRating', models.IntegerField()),
            ],
            options={
                'db_table': 'GameReviews',
            },
        ),
    ]
