# Generated by Django 5.0.3 on 2024-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamereviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereviews',
            name='hoursPlayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamereviews',
            name='notes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamereviews',
            name='overallRating',
            field=models.IntegerField(editable=False),
        ),
    ]
