# Generated by Django 5.0.3 on 2024-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gamereviews_hoursplayed_gamereviews_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereviews',
            name='imgLink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
