# Generated by Django 5.0.3 on 2024-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gamereviews_imglink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toiletName', models.CharField(max_length=255)),
                ('imgLink', models.CharField(max_length=255)),
                ('cleanliness', models.IntegerField()),
                ('toiletPaper', models.IntegerField()),
                ('smell', models.IntegerField()),
                ('bidetNozzle', models.IntegerField()),
                ('soap', models.IntegerField()),
                ('comfort', models.IntegerField()),
                ('lighting', models.IntegerField()),
                ('airiness', models.IntegerField()),
                ('doorLock', models.IntegerField()),
                ('flush', models.IntegerField()),
                ('overallRating', models.IntegerField(editable=False)),
            ],
            options={
                'db_table': 'ToiletReview',
            },
        ),
    ]
