# Generated by Django 5.0.3 on 2024-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_toiletreview_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=255)),
                ('artistName', models.CharField(max_length=255)),
                ('imgLink', models.CharField(max_length=255)),
                ('yearReleased', models.IntegerField()),
                ('overallRating', models.IntegerField()),
            ],
            options={
                'db_table': 'AlbumReview',
            },
        ),
    ]
